spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: libro-service
          uri: http://localhost:8081
          predicates:
            - Path=/libros/**
        - id: autor-service
          uri: http://localhost:8082
          predicates:
            - Path=/autores/**
server:
  port: 8080
